import test from 'node:test';
import assert from 'node:assert/strict';
import { buildBracketModel,calculateBracketLayout } from '../src/tournament-presentation.js';

const teams=count=>Array.from({length:count},(_,index)=>`team-${index+1}`);
const pair=ids=>Array.from({length:ids.length/2},(_,index)=>ids.slice(index*2,index*2+2));
const tournament=(openingRound,ids)=>({bracket:{roundOf16:openingRound==='roundOf16'?pair(ids):[],quarterfinals:openingRound==='quarterfinals'?pair(ids):[],semifinals:openingRound==='semifinals'?pair(ids):[],final:[]},winners:{roundOf16:[],quarterfinals:[],semifinals:[],final:[]},champion:null});

test('8-team format renders only semifinals, final, and champion',()=>{const model=buildBracketModel(8,tournament('semifinals',teams(4)));assert.deepEqual(model.rounds,['semifinals','final','champion']);assert.deepEqual(model.columns.map(column=>column.nodes.length),[4,2,1]);assert.deepEqual(model.columns[1].nodes.map(node=>node.label),['Winner SF1','Winner SF2']);});
test('16-team format renders the complete quarterfinal path',()=>{const state=tournament('quarterfinals',teams(8)),model=buildBracketModel(16,state);assert.deepEqual(model.rounds,['quarterfinals','semifinals','final','champion']);assert.deepEqual(model.columns.map(column=>column.nodes.length),[8,4,2,1]);assert.deepEqual(model.columns[1].nodes.map(node=>node.label),['Winner QF1','Winner QF2','Winner QF3','Winner QF4']);assert.deepEqual(model.columns[2].nodes.map(node=>node.label),['Winner SF1','Winner SF2']);});
test('32-team format renders all five connected elimination levels',()=>{const model=buildBracketModel(32,tournament('roundOf16',teams(16)));assert.deepEqual(model.rounds,['roundOf16','quarterfinals','semifinals','final','champion']);assert.deepEqual(model.columns.map(column=>column.nodes.length),[16,8,4,2,1]);});
test('completed winners replace future-round placeholders without changing pairings',()=>{const state=tournament('quarterfinals',teams(8));state.winners.quarterfinals=['team-1','team-3','team-5','team-7'];state.winners.semifinals=['team-1','team-7'];state.champion='team-7';const model=buildBracketModel(16,state);assert.deepEqual(model.columns[0].nodes.map(node=>node.teamId),teams(8));assert.deepEqual(model.columns[1].nodes.map(node=>node.teamId),state.winners.quarterfinals);assert.deepEqual(model.columns[2].nodes.map(node=>node.teamId),state.winners.semifinals);assert.equal(model.columns[3].nodes[0].teamId,'team-7');});
test('calculated nodes and continuous connectors remain inside presentation safe margins',()=>{for(const [teamCount,round,count,connectors] of [[8,'semifinals',4,3],[16,'quarterfinals',8,7],[32,'roundOf16',16,15]]){const model=buildBracketModel(teamCount,tournament(round,teams(count))),layout=calculateBracketLayout(model),halfW=layout.dimensions.width/2,halfH=layout.dimensions.height/2;assert.equal(layout.connectors.length,connectors);layout.columnXs.forEach(x=>{assert.ok(x-halfW>=layout.safe.left);assert.ok(x+halfW<=layout.safe.right);});layout.positions.flat().forEach(y=>{assert.ok(y-halfH>=310);assert.ok(y+halfH<=900);});layout.connectors.forEach(line=>{assert.equal(line.targetY,(line.yA+line.yB)/2);assert.ok(line.fromX<line.midX&&line.midX<line.toX);});}});
