import test from 'node:test';
import assert from 'node:assert/strict';
import { detectDeviceMode } from '../src/device-mode.js';
import { sanitizeVideoFilename,selectRecordingFormat,verifyRecordedContainer } from '../src/recording-controller.js';

const environment=({width=1440,fine=true,coarse=false,touch=0,recorder=true,capture=true}={})=>({innerWidth:width,matchMedia:query=>({matches:query.includes('fine')?fine:coarse}),navigator:{maxTouchPoints:touch},MediaRecorder:recorder?function Recorder(){}:undefined,HTMLCanvasElement:capture?function Canvas(){}:undefined});
test('desktop capability detection enables Creator Mode without relying on user agent',()=>{const env=environment();env.HTMLCanvasElement.prototype.captureStream=()=>{};assert.equal(detectDeviceMode(env).mode,'creator');});
test('phone, coarse-pointer TV, and missing recorder use Watch Mode',()=>{for(const env of [environment({width:430,fine:false,coarse:true,touch:5}),environment({width:1920,fine:false,coarse:true}),environment({recorder:false})]){if(env.HTMLCanvasElement)env.HTMLCanvasElement.prototype.captureStream=()=>{};assert.equal(detectDeviceMode(env).mode,'watch');}});
test('public deployment enables full Online Mode independently of device capabilities',()=>{for(const env of [environment({width:430,fine:false,coarse:true,touch:5,recorder:false,capture:false}),environment({width:1920,fine:false,coarse:true,recorder:false,capture:false}),environment()]){const mode=detectDeviceMode(env,'online');assert.equal(mode.mode,'online');assert.equal(mode.online,true);assert.equal(mode.creator,false);assert.equal(mode.recordingSupported,false);}});
test('recording always captures a WebM intermediate for post-tournament MP4 conversion',()=>{const both={isTypeSupported:type=>type.startsWith('video/mp4')||type==='video/webm;codecs=vp8,opus'};assert.deepEqual(selectRecordingFormat(both),{mimeType:'video/webm;codecs=vp8,opus',container:'webm'});const mp4Only={isTypeSupported:type=>type.startsWith('video/mp4')};assert.equal(selectRecordingFormat(mp4Only),null);});
test('download filenames are sanitized and container signatures are verified',async()=>{assert.equal(sanitizeVideoFilename('Copa América',2026),'Copa-America-Marble-Football-2026.mp4');const mp4=new Blob([new Uint8Array([0,0,0,16,102,116,121,112,105,115,111,109])]),webm=new Blob([new Uint8Array([0x1a,0x45,0xdf,0xa3])]);assert.equal(await verifyRecordedContainer(mp4,'mp4'),true);assert.equal(await verifyRecordedContainer(webm,'webm'),true);assert.equal(await verifyRecordedContainer(webm,'mp4'),false);});
