import test from 'node:test';
import assert from 'node:assert/strict';
import { TEAM_BY_ID } from '../src/team-data.js';
import { createTournamentConfig,validateTournamentConfig } from '../src/tournament-config.js';
import { TOURNAMENT_PRESETS,eligibleTeams } from '../src/tournament-presets.js';

const ids=config=>new Set(eligibleTeams(config).map(team=>team.id));
const selected=config=>Object.values(config.groups).flat();

test('AFCON defaults to 16 CAF teams and excludes Japan, France, and Brazil',()=>{const config=createTournamentConfig({tournamentType:'AFCON'}),pool=ids(config);assert.equal(config.tournamentTitle,'Africa Cup of Nations');assert.equal(config.teamCount,16);assert.ok(['nigeria','egypt','morocco','senegal','ghana','cameroon','tunisia','algeria','mali','ivory-coast','south-africa','dr-congo','angola','zambia','burkina-faso','cape-verde'].every(id=>pool.has(id)));assert.ok(['japan','france','brazil'].every(id=>!pool.has(id)));assert.ok(selected(config).every(id=>TEAM_BY_ID[id].confederation==='CAF'));assert.equal(validateTournamentConfig(config).valid,true);});
test('Asian Cup defaults to 16 AFC teams and excludes African and European teams',()=>{const config=createTournamentConfig({tournamentType:'ASIAN_CUP'}),pool=ids(config);assert.equal(config.tournamentTitle,'AFC Asian Cup');assert.equal(config.teamCount,16);assert.ok(['iran','japan','saudi-arabia','iraq','south-korea','qatar'].every(id=>pool.has(id)));assert.ok(!pool.has('morocco'));assert.ok(!pool.has('france'));assert.equal(validateTournamentConfig(config).valid,true);});
test('EURO defaults to a valid 16-team UEFA field',()=>{const config=createTournamentConfig({tournamentType:'EURO'});assert.equal(config.tournamentTitle,'UEFA European Championship');assert.equal(config.teamCount,16);assert.ok(selected(config).every(id=>TEAM_BY_ID[id].confederation==='UEFA'));assert.equal(validateTournamentConfig(config).valid,true);});
test('World Cup defaults to a valid mixed 32-team field',()=>{const config=createTournamentConfig({tournamentType:'WORLD_CUP'}),confeds=new Set(selected(config).map(id=>TEAM_BY_ID[id].confederation));assert.equal(config.tournamentTitle,'FIFA WORLD CUP');assert.equal(config.teamCount,32);assert.ok(confeds.size>3);assert.equal(validateTournamentConfig(config).valid,true);});
test('CUSTOM supports every confederation and custom filters',()=>{const all=createTournamentConfig({tournamentType:'CUSTOM'});assert.equal(ids(all).size,211);const caf=createTournamentConfig({tournamentType:'CUSTOM',confederationFilter:'CAF',teamCount:8});assert.equal(ids(caf).size,54);assert.ok(selected(caf).every(id=>TEAM_BY_ID[id].confederation==='CAF'));assert.equal(validateTournamentConfig(caf).valid,true);});
test('regional presets validate and Copa América invitations are opt-in',()=>{const goldCup=createTournamentConfig({tournamentType:'CONCACAF_GOLD_CUP'}),ofc=createTournamentConfig({tournamentType:'OFC_NATIONS_CUP'}),copa=createTournamentConfig({tournamentType:'COPA_AMERICA'}),invited=createTournamentConfig({tournamentType:'COPA_AMERICA',teamCount:16,allowInvitedTeams:true});assert.equal(validateTournamentConfig(goldCup).valid,true);assert.equal(validateTournamentConfig(ofc).valid,true);assert.equal(validateTournamentConfig(copa).valid,true);assert.ok(selected(copa).every(id=>TEAM_BY_ID[id].confederation==='CONMEBOL'));assert.equal(validateTournamentConfig(invited).valid,true);assert.ok(selected(invited).some(id=>TEAM_BY_ID[id].confederation!=='CONMEBOL'));});
test('preset titles and defaults are complete',()=>{assert.deepEqual(Object.fromEntries(Object.entries(TOURNAMENT_PRESETS).map(([key,preset])=>[key,[preset.title,preset.defaultTeamCount]])),{CUSTOM:['MARBLE CHAMPIONS CUP',32],WORLD_CUP:['FIFA WORLD CUP',32],AFCON:['Africa Cup of Nations',16],ASIAN_CUP:['AFC Asian Cup',16],EURO:['UEFA European Championship',16],COPA_AMERICA:['Copa América',8],CONCACAF_GOLD_CUP:['CONCACAF Gold Cup',16],OFC_NATIONS_CUP:['OFC Nations Cup',8]});});
