const CHANNELS=['music','crowd','game','presentation'];
const DEFAULTS={music:false,trackId:null,musicVolume:.3,crowd:false,crowdVolume:.16,sfx:true};

export async function loadAudioManifest(path='audio/music/manifest.json'){try{const response=await fetch(path,{cache:'no-store'});if(!response.ok)return[];const data=await response.json();return Array.isArray(data.tracks)?data.tracks:[];}catch{return[];}}

export class AudioMixer{
  constructor(){this.context=null;this.master=null;this.destination=null;this.channels={};this.buffers=new Map();this.sources={};this.settings={...DEFAULTS};this.cooldowns=new Map();this.musicBase=.3;this.importedMusicGain=null;this.importedMusicStartedAt=null;}
  initialize(settings={}){this.settings={...DEFAULTS,...settings};const AudioContext=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContext)return false;this.context??=new AudioContext();this.master=this.context.createGain();this.master.gain.value=.92;this.master.connect(this.context.destination);this.destination=this.context.createMediaStreamDestination();this.master.connect(this.destination);CHANNELS.forEach(name=>{const gain=this.context.createGain();gain.gain.value=name==='music'?this.settings.musicVolume:name==='crowd'?this.settings.crowdVolume:1;gain.connect(this.master);this.channels[name]=gain;});this.importedMusicGain=this.context.createGain();this.importedMusicGain.gain.value=this.settings.musicVolume;this.importedMusicGain.connect(this.context.destination);this.musicBase=this.settings.musicVolume;this.context.resume();return true;}
  async loadBuffer(file){if(!this.context||!file)return null;if(this.buffers.has(file))return this.buffers.get(file);try{const bytes=file instanceof Blob?await file.arrayBuffer():await (await fetch(file)).arrayBuffer(),buffer=await this.context.decodeAudioData(bytes);this.buffers.set(file,buffer);return buffer;}catch{return null;}}
  async configure(manifest=[]){if(!this.context)return;if(this.settings.music&&this.settings.trackId){const imported=this.settings.musicFile,track=manifest.find(item=>item.id===this.settings.trackId),buffer=await this.loadBuffer(imported??track?.file);if(!buffer)throw new Error('The selected music file could not be decoded.');if(imported)this.startImportedMusic(buffer);else this.startLoop('music',buffer);}const crowd=await loadAudioManifest('audio/crowd/manifest.json'),crowdBuffer=this.settings.crowd?await this.loadBuffer(crowd[0]?.file):null;if(crowdBuffer)this.startLoop('crowd',crowdBuffer);const sfx=await loadAudioManifest('audio/sfx/manifest.json');await Promise.all(sfx.map(async item=>{const buffer=await this.loadBuffer(item.file);if(buffer)this.buffers.set(`sfx:${item.id}`,buffer);}));}
  startLoop(channel,buffer){this.sources[channel]?.stop();const source=this.context.createBufferSource();source.buffer=buffer;source.loop=true;source.connect(this.channels[channel]);source.start();this.sources[channel]=source;}
  startImportedMusic(buffer){this.sources.importedMusic?.stop();const source=this.context.createBufferSource();source.buffer=buffer;source.loop=true;source.connect(this.importedMusicGain);source.start();this.sources.importedMusic=source;this.importedMusicStartedAt=this.context.currentTime;}
  stopMusic(){for(const name of ['music','importedMusic']){try{this.sources[name]?.stop();}catch{}delete this.sources[name];}this.importedMusicStartedAt=null;}
  play(id,{channel='game',cooldown=120,volume=1,duck=false}={}){if(!this.context||!this.settings.sfx)return;const now=performance.now(),last=this.cooldowns.get(id)??-Infinity;if(now-last<cooldown)return;this.cooldowns.set(id,now);const buffer=this.buffers.get(`sfx:${id}`);if(!buffer)return;const source=this.context.createBufferSource(),gain=this.context.createGain();gain.gain.value=volume;source.buffer=buffer;source.connect(gain);gain.connect(this.channels[channel]);source.start();if(duck)this.duckMusic();}
  duckMusic(duration=1300){if(!this.context||!this.channels.music)return;const gain=this.channels.music.gain,now=this.context.currentTime;gain.cancelScheduledValues(now);gain.setValueAtTime(gain.value,now);gain.linearRampToValueAtTime(this.musicBase*.52,now+.12);gain.linearRampToValueAtTime(this.musicBase,now+duration/1000);}
  setStage(stage){if(!this.context||!this.channels.crowd)return;const multiplier=/FINAL/.test(stage)?1.65:/SEMIFINAL/.test(stage)?1.35:1,gain=this.channels.crowd.gain,now=this.context.currentTime;gain.cancelScheduledValues(now);gain.linearRampToValueAtTime(this.settings.crowdVolume*multiplier,now+.8);}
  boostCrowd(duration=1800){if(!this.context||!this.channels.crowd||!this.settings.crowd)return;const gain=this.channels.crowd.gain,now=this.context.currentTime,base=this.settings.crowdVolume;gain.cancelScheduledValues(now);gain.linearRampToValueAtTime(Math.min(.5,base*2.4),now+.18);gain.linearRampToValueAtTime(base,now+duration/1000);}
  event(name){const map={'match-start':['whistle',{channel:'presentation',cooldown:1000,duck:true}],'marble-impact':['marble-impact',{cooldown:180,volume:.45}],'power-fan':['power-fan',{cooldown:220,volume:.8}],'goalkeeper-save':['goalkeeper-save',{cooldown:350,volume:.8}],'goal':['goal',{channel:'presentation',cooldown:900,duck:true}],'qualification':['qualification',{channel:'presentation',cooldown:1200,duck:true}],'knockout-victory':['knockout-victory',{channel:'presentation',cooldown:1500,duck:true}],'champion':['champion',{channel:'presentation',cooldown:3000,duck:true}]};const entry=map[name];if(entry)this.play(entry[0],entry[1]);if(name==='goal'||name==='champion')this.boostCrowd(name==='champion'?3200:1800);}
  get importedMusic(){return this.settings.music&&this.settings.musicFile?{blob:this.settings.musicFile,filename:this.settings.musicTitle||this.settings.musicFile.name,type:this.settings.musicFile.type,volume:this.settings.musicVolume}:null;}
  get recordingStream(){return this.destination?.stream??null;}
}
