import { AudioMixer,loadAudioManifest } from './audio-mixer.js';

class MediaRuntime{
  constructor(){this.audio=new AudioMixer();this.recordRequested=false;this.recording=false;this.phase='SETUP';this.hud=null;this.result=null;this.recorder=null;this.timeline=[];this.webmRecovery=null;this.webmRecoveryUrl=null;this.championPresentationFinished=false;this.endCardFinished=false;this.beforeUnload=event=>{if(this.recording){event.preventDefault();event.returnValue='';}};}
  async prepare(settings,recordRequested){this.recordRequested=recordRequested;const audioReady=this.audio.initialize(settings);if(recordRequested&&!audioReady)throw new Error('Web Audio recording is not supported in this browser.');const [manifest,recordingModule]=await Promise.all([loadAudioManifest(),recordRequested?import('./recording-controller.js'):Promise.resolve(null)]);await this.audio.configure(manifest);if(recordingModule&&!this.recorder){const {TournamentRecorder}=recordingModule;this.recorder=new TournamentRecorder({onStatus:status=>this.updateStatus(status),onComplete:result=>this.handleRecordingComplete(result),onError:(error,partial)=>this.showError(error,partial),onUnexpectedStop:(partial,error)=>{console.error('Unexpected recorder stop.',{phase:this.phase,timeline:this.timeline,recorder:this.recorder?.snapshot?.(),error});this.showError(error,partial);}});}}
  async attachStage(canvas,tournamentConfig){if(!this.recordRequested)return;try{this.recorder.prepare(canvas,this.audio.recordingStream,tournamentConfig.tournamentTitle);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await new Promise(resolve=>setTimeout(resolve,750));this.recorder.start();this.recording=true;this.note('START');window.addEventListener('beforeunload',this.beforeUnload);this.showHud();}catch(error){this.showError(error);}}
  event(name){this.audio.event(name);if(name==='champion'&&!this.recording)setTimeout(()=>this.audio.stopMusic(),6500);}
  setPhase(phase){this.phase=phase;this.audio.setStage(phase);this.updateStatus({recording:this.recording,elapsedMs:this.recorder?.startedAt?Date.now()-this.recorder.startedAt:0});}
  showHud(){this.hud?.remove();this.hud=document.createElement('aside');this.hud.className='recording-hud';this.hud.setAttribute('aria-label','Recording status');this.hud.innerHTML='<strong>● REC <time>00:00</time></strong>';document.body.appendChild(this.hud);}
  updateStatus({recording,elapsedMs=0}){if(!this.hud)return;const seconds=Math.floor(elapsedMs/1000),minutes=Math.floor(seconds/60),text=`${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;this.hud.querySelector('time').textContent=text;if(!recording)this.hud.remove();}
  note(label){const elapsedMs=this.recorder?.startedAt?Date.now()-this.recorder.startedAt:0;this.timeline.push({label,elapsedMs});}
  debugSnapshot(){return{requested:this.recordRequested,recording:this.recording,recorder:this.recorder?.snapshot?.()??null,timeline:[...this.timeline]};}
  markChampionPresented(){this.championPresentationFinished=true;}
  markEndCardFinished(){this.endCardFinished=true;}
  async finish(tournamentState){if(!this.recording)return null;if(tournamentState!=='complete'||!this.championPresentationFinished||!this.endCardFinished){console.error('Ignored premature recording stop request.',{tournamentState,championPresentationFinished:this.championPresentationFinished,endCardFinished:this.endCardFinished,phase:this.phase});return null;}this.recording=false;window.removeEventListener('beforeunload',this.beforeUnload);try{return await this.recorder.stop();}catch(error){this.showError(error,this.recorder.partialResult());return null;}finally{this.audio.stopMusic();}}
  async handleRecordingComplete(webm,panel=null){if(this.webmRecovery!==webm)this.note('STOP');this.webmRecovery=webm;this.webmRecoveryUrl??=URL.createObjectURL(webm.blob);console.info('[MP4 1/11] WebM finalized.',{durationMs:webm.durationMs});console.info('[MP4 2/11] WebM size known.',{bytes:webm.blob.size});panel??=this.showConversionState('LOADING VIDEO CONVERTER...','Preserving WebM backup.',webm);this.updateConversionState(panel,'LOADING VIDEO CONVERTER...','Loading conversion package.',webm);try{console.info('[MP4 3/11] FFmpeg package import started.');const module=await import('./mp4-converter.js');console.info('[MP4 4/11] FFmpeg package imported.',module.FFMPEG_ASSETS);const mp4=await module.convertWebMToMp4(webm.blob,{title:webm.title,durationMs:webm.durationMs,music:this.audio.importedMusic,onState:state=>this.applyConverterState(panel,state,webm),onProgress:value=>this.updateConversion(panel,value,webm)});this.showDownload(mp4,webm,panel);}catch(error){console.error('MP4 conversion failed.',{error,webmBytes:webm.blob.size});this.showConversionFailure(error,webm,panel);}}
  showConversionState(title,message,webm){const panel=document.createElement('section');panel.className='video-ready conversion-progress';document.body.appendChild(panel);this.updateConversionState(panel,title,message,webm);return panel;}
  backupLink(webm,label='DOWNLOAD WEBM BACKUP'){return`<a class="secondary-download" download="${webm.filename}" href="${this.webmRecoveryUrl}" data-bytes="${webm.blob.size}" data-mime="${webm.blob.type}">${label}</a>`;}
  updateConversionState(panel,title,message,webm){panel.innerHTML=`<div><small>TOURNAMENT COMPLETE</small><h2>${title}</h2><p data-conversion-progress>${message}</p>${this.backupLink(webm)}</div>`;}
  applyConverterState(panel,{state,message},webm){if(state==='loading-module')this.updateConversionState(panel,'LOADING FFMPEG MODULE...',message,webm);else if(state==='loading-core')this.updateConversionState(panel,'LOADING FFMPEG CORE...',message,webm);else if(state==='loading-wasm')this.updateConversionState(panel,'CHECKING FFMPEG RUNTIME...',message,webm);else if(state==='starting-worker')this.updateConversionState(panel,'STARTING LOCAL FFMPEG...',message,webm);else if(state==='uploading'||state==='uploading-music'||state==='writing-input')this.updateConversionState(panel,'PREPARING RECORDING...',message,webm);else if(state==='ready')this.updateConversionState(panel,'FFMPEG READY',message,webm);else if(state==='converting')this.updateConversionState(panel,'CONVERTING TO MP4','Waiting for first FFmpeg progress update…',webm);else if(state==='validating')this.updateConversionState(panel,'VALIDATING MP4...',message,webm);}
  updateConversion(panel,progress,webm){const title=panel?.querySelector('h2'),output=panel?.querySelector('[data-conversion-progress]');if(title)title.textContent='CONVERTING TO MP4';if(output)output.textContent=`${progress<1?progress.toFixed(1):Math.round(progress)}%`;if(!panel.querySelector('.secondary-download'))panel.querySelector('div')?.insertAdjacentHTML('beforeend',this.backupLink(webm));}
  showDownload(result,webm,panel=this.showConversionState('VIDEO READY','',webm)){this.result=result;const url=URL.createObjectURL(result.blob);panel.innerHTML=`<div><small>TOURNAMENT COMPLETE</small><h2>VIDEO READY</h2><p>Genuine H.264/AAC MP4 recording ready.</p><a download="${result.filename}" href="${url}" data-bytes="${result.blob.size}" data-mime="${result.blob.type}">DOWNLOAD MP4</a>${this.backupLink(webm)}</div>`;}
  showConversionFailure(error,webm,panel=this.showConversionState('MP4 CONVERSION FAILED','',webm)){const timeout=error?.code==='CONVERTER_TIMEOUT',title=timeout?'MP4 CONVERTER NOT RESPONDING':'MP4 CONVERSION FAILED';panel.innerHTML=`<div><small>TOURNAMENT COMPLETE</small><h2>${title}</h2><p>${error?.message??error}</p><button type="button" data-retry-conversion>RETRY MP4 CONVERSION</button>${this.backupLink(webm,'DOWNLOAD WEBM RECOVERY')}</div>`;panel.querySelector('[data-retry-conversion]')?.addEventListener('click',()=>this.handleRecordingComplete(webm,panel),{once:true});}
  showError(error,partial=null){this.recording=false;window.removeEventListener('beforeunload',this.beforeUnload);this.hud?.remove();const notice=document.createElement('div');notice.className='recording-error';notice.textContent=`Recording failed: ${error?.message??error}`;if(partial?.blob?.size){const url=URL.createObjectURL(partial.blob),link=document.createElement('a');link.href=url;link.download=partial.filename;link.textContent='DOWNLOAD PARTIAL RECORDING';notice.append(document.createElement('br'),link);}document.body.appendChild(notice);}
}
export const mediaRuntime=new MediaRuntime();
