import { loadAudioManifest } from './audio-mixer.js';

const ACCEPTED_MUSIC=/\.(mp3|wav|m4a|ogg)$/i;

export async function showRuntimeLaunch(deviceMode,onLaunch){
  const [tracks,crowdTracks,sfxTracks]=await Promise.all([loadAudioManifest(),loadAudioManifest('audio/crowd/manifest.json'),loadAudioManifest('audio/sfx/manifest.json')]),shell=document.querySelector('#game-shell'),root=document.createElement('section');root.className='runtime-launch';shell.appendChild(root);
  if(deviceMode.online){root.innerHTML=`<div class="runtime-card online"><small>ONLINE MODE</small><h2>TOURNAMENT READY</h2><p>Your complete interactive tournament is configured and ready.</p><label class="fullscreen-choice"><input id="fullscreen" type="checkbox" checked> Use fullscreen when supported</label><button id="online-start" type="button">START TOURNAMENT</button></div>`;const start=root.querySelector('#online-start');start.focus({preventScroll:true});return new Promise(resolve=>start.onclick=async()=>{const fullscreen=root.querySelector('#fullscreen').checked&&document.fullscreenEnabled?shell.requestFullscreen().catch(()=>{}):Promise.resolve();await onLaunch({music:false,crowd:false,sfx:true},false);await fullscreen;root.remove();resolve({record:false});});}
  if(deviceMode.watch){root.innerHTML=`<div class="runtime-card"><small>WATCH MODE</small><h2>TOURNAMENT READY</h2><p>The complete 16:9 tournament will fit this screen.</p><label class="fullscreen-choice"><input id="fullscreen" type="checkbox" checked> Use fullscreen when supported</label><button id="watch">WATCH TOURNAMENT</button></div>`;return new Promise(resolve=>root.querySelector('#watch').onclick=async()=>{const fullscreen=root.querySelector('#fullscreen').checked&&document.fullscreenEnabled?shell.requestFullscreen().catch(()=>{}):Promise.resolve();await onLaunch({music:false,crowd:false,sfx:true},false);await fullscreen;root.remove();resolve({record:false});});}
  const options=tracks.map(track=>`<option value="${track.id}">${track.title}</option>`).join(''),importedTracks=[];root.innerHTML=`<div class="runtime-card creator"><small>CREATOR MODE</small><h2>TOURNAMENT OUTPUT</h2><section class="audio-settings"><h3>AUDIO</h3><label><span>MUSIC</span><input id="music" type="checkbox" ${tracks.length?'':'disabled'}></label><label><span>TRACK</span><select id="track" ${tracks.length?'':'disabled'}>${tracks.length?options:'<option value="">No approved tracks installed</option>'}</select></label><div class="music-import-row"><input id="music-import" type="file" accept=".mp3,.wav,.m4a,.ogg,audio/mpeg,audio/wav,audio/mp4,audio/ogg" multiple hidden><button id="import-music" type="button">IMPORT MUSIC</button></div><label><span>MUSIC VOLUME</span><input id="music-volume" type="range" min="0" max="1" step=".05" value=".3"></label><label><span>CROWD</span><input id="crowd" type="checkbox" ${crowdTracks.length?'':'disabled'}></label><label><span>SFX</span><input id="sfx" type="checkbox" ${sfxTracks.length?'checked':'disabled'}></label><p data-audio-note>${tracks.length||crowdTracks.length||sfxTracks.length?'License details are loaded from the approved audio manifests.':'Import local music or continue with the existing silent recording audio.'}</p></section><p id="runtime-error" class="runtime-error-text"></p><div class="launch-actions"><button id="play">PLAY WITHOUT RECORDING</button><button id="record">● RECORD TOURNAMENT</button></div></div>`;
  const music=root.querySelector('#music'),track=root.querySelector('#track'),picker=root.querySelector('#music-import'),error=root.querySelector('#runtime-error');root.querySelector('#import-music').onclick=()=>picker.click();picker.onchange=()=>{error.textContent='';for(const file of picker.files){if(!ACCEPTED_MUSIC.test(file.name)){error.textContent=`Unsupported music file: ${file.name}`;continue;}const id=`imported:${crypto.randomUUID()}`;importedTracks.push({id,file,title:file.name});const option=document.createElement('option');option.value=id;option.textContent=file.name;track.appendChild(option);track.value=id;track.disabled=false;music.disabled=false;music.checked=true;}picker.value='';};
  const settings=()=>{const selected=track.value,imported=importedTracks.find(item=>item.id===selected);return{music:music.checked,trackId:selected||null,musicFile:imported?.file??null,musicTitle:imported?.title??null,musicVolume:Number(root.querySelector('#music-volume').value),crowd:root.querySelector('#crowd').checked,sfx:root.querySelector('#sfx').checked};};return new Promise(resolve=>{const launch=async record=>{try{await onLaunch(settings(),record);root.remove();resolve({record});}catch(launchError){error.textContent=launchError?.message??String(launchError);}};root.querySelector('#play').onclick=()=>launch(false);root.querySelector('#record').onclick=()=>launch(true);});
}
