import { TEAMS } from './team-data.js';
import { createTournamentConfig,groupsForTeamCount,validateTournamentConfig } from './tournament-config.js';
import { CONFEDERATION_FILTERS,TOURNAMENT_PRESETS,TOURNAMENT_TYPES,eligibleTeams,presetFor } from './tournament-presets.js';

const esc=value=>String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const teamSelector=(group,index,id)=>{const team=TEAMS.find(item=>item.id===id);return`<span class="team-select" data-team-select="${group}-${index}"><button type="button" class="team-select-trigger ${team?'':'empty'}" data-team-trigger data-group="${group}" data-index="${index}" aria-haspopup="listbox" aria-expanded="false">${team?`<img src="${team.flag}" alt=""><span>${team.name}</span>`:'<span>SELECT TEAM</span>'}<b aria-hidden="true">⌄</b></button>${team?`<button type="button" class="team-select-clear" data-team-clear data-group="${group}" data-index="${index}" aria-label="Clear ${team.name}">×</button>`:''}<span class="team-select-popup" data-team-popup hidden><input type="search" data-team-search placeholder="Search country or code…" autocomplete="off" aria-label="Search teams"><span class="team-select-results" data-team-results role="listbox"></span></span></span>`;};

export function showTournamentSetup(){return new Promise(resolve=>{
  let step=1,state=createTournamentConfig();const shell=document.querySelector('#game-shell'),root=document.createElement('section');root.className='setup';shell.appendChild(root);
  const focusable=()=>[...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled])')].filter(element=>{const box=element.getBoundingClientRect();return box.width>0&&box.height>0;});
  const moveFocus=(current,key)=>{const source=current.getBoundingClientRect(),sx=source.left+source.width/2,sy=source.top+source.height/2,direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[key],candidates=focusable().filter(element=>element!==current).map(element=>{const box=element.getBoundingClientRect(),dx=box.left+box.width/2-sx,dy=box.top+box.height/2-sy,primary=direction[0]?dx*direction[0]:dy*direction[1],secondary=Math.abs(direction[0]?dy:dx);return{element,primary,score:primary*1000+secondary};}).filter(item=>item.primary>2).sort((a,b)=>a.score-b.score);if(candidates[0])candidates[0].element.focus({preventScroll:true});};
  const remoteNavigation=event=>{const open=root.querySelector('[data-team-popup]:not([hidden])');if((event.key==='Escape'||event.key==='BrowserBack'||event.key==='Backspace')&&!event.target.matches('input[type="text"],input[type="search"],input[type="number"]')){if(open){event.preventDefault();open.hidden=true;const trigger=open.closest('[data-team-select]')?.querySelector('[data-team-trigger]');trigger?.setAttribute('aria-expanded','false');trigger?.focus({preventScroll:true});return;}const back=root.querySelector('#back');if(back){event.preventDefault();back.click();}return;}if(!event.key.startsWith('Arrow')||open)return;const target=document.activeElement;if(!root.contains(target)||target.matches('input,select,textarea'))return;event.preventDefault();moveFocus(target,event.key);};document.addEventListener('keydown',remoteNavigation);
  const closeTeamSelectors=except=>root.querySelectorAll('[data-team-popup]').forEach(popup=>{if(popup!==except){popup.hidden=true;popup.closest('[data-team-select]')?.querySelector('[data-team-trigger]')?.setAttribute('aria-expanded','false');}});
  const dismissTeamSelectors=event=>{if(!root.contains(event.target)||!event.target.closest('[data-team-select]'))closeTeamSelectors();};document.addEventListener('pointerdown',dismissTeamSelectors);
  const selectedIds=()=>Object.values(state.groups).flat().filter(Boolean);
  const resetWith=changes=>{state=createTournamentConfig({...state,...changes,groups:undefined,teamStrengths:{},preselectedFinalists:[],preselectedChampion:null});render();};
  const refreshTeamSelector=(group,index)=>{const current=root.querySelector(`[data-team-select="${group}-${index}"]`);if(current)current.outerHTML=teamSelector(group,index,state.groups[group][index]);bind();requestAnimationFrame(()=>root.querySelector(`[data-team-select="${group}-${index}"] [data-team-trigger]`)?.focus({preventScroll:true}));};
  const render=()=>{
    const letters=groupsForTeamCount(state.teamCount),preset=presetFor(state.tournamentType),teams=selectedIds().map(id=>TEAMS.find(team=>team.id===id)).filter(Boolean);let body='';
    if(step===1)body=`<h2>TOURNAMENT TYPE</h2><div class="preset-grid">${TOURNAMENT_TYPES.map(type=>{const item=TOURNAMENT_PRESETS[type];return`<button class="choice ${state.tournamentType===type?'active':''}" data-type="${type}">${item.label}<small>${item.confederation==='ALL'?'ALL CONFEDERATIONS':item.confederation}</small></button>`;}).join('')}</div>`;
    if(step===2)body=`<h2>TOURNAMENT DETAILS</h2><label class="setup-label compact">TOURNAMENT TITLE<input id="title" maxlength="48" value="${esc(state.tournamentTitle)}" placeholder="TOURNAMENT TITLE"></label>${state.tournamentType==='CUSTOM'?`<h3 class="setup-section-title">CONFEDERATION FILTER</h3><div class="filter-grid">${CONFEDERATION_FILTERS.map(filter=>`<button class="filter-choice ${state.confederationFilter===filter?'active':''}" data-filter="${filter}">${filter}</button>`).join('')}</div>`:`<p class="preset-summary"><strong>${preset.label}</strong><span>TEAM POOL: ${preset.confederation==='ALL'?'ALL CONFEDERATIONS':preset.confederation}</span></p>`}`;
    if(step===3)body=`<h2>NUMBER OF TEAMS</h2><div class="choice-grid">${preset.teamCounts.map(n=>`<button class="choice ${state.teamCount===n?'active':''}" data-count="${n}">${n} TEAMS<small>${n/4} GROUPS × 4</small></button>`).join('')}</div>${state.tournamentType==='COPA_AMERICA'&&state.teamCount===16?`<h3 class="setup-section-title">INVITED TEAMS</h3><div class="toggle-row"><button class="choice ${!state.allowInvitedTeams?'active':''}" data-invites="no">CONMEBOL ONLY</button><button class="choice ${state.allowInvitedTeams?'active':''}" data-invites="yes">ALLOW INVITED TEAMS</button></div><p class="hint">Enable invited teams to complete a 16-team field.</p>`:''}`;
    if(step===4)body=`<h2>TEAM SELECTION AND GROUPS</h2><p class="pool-label">${state.confederationFilter==='ALL'||state.allowInvitedTeams?'ALL CONFEDERATIONS':state.confederationFilter} TEAM POOL</p><div class="groups-editor">${letters.map(letter=>`<fieldset><legend>GROUP ${letter}</legend>${state.groups[letter].map((id,i)=>`<div class="team-slot"><span>TEAM ${i+1}</span>${teamSelector(letter,i,id)}</div>`).join('')}</fieldset>`).join('')}</div>`;
    if(step===5)body=`<h2>CUSTOM TEAM STRENGTH? <small>OPTIONAL</small></h2><div class="toggle-row"><button class="choice ${!state.teamStrengthEnabled?'active':''}" data-strength="no">NO — BALANCED TOURNAMENT</button><button class="choice ${state.teamStrengthEnabled?'active':''}" data-strength="yes">YES — SET TEAM STRENGTH</button></div>${state.teamStrengthEnabled?`<p class="hint">TEAM STRENGTH: 50 Average · 65 Strong · 80 Very Strong · 90 Favorite</p><div class="strength-grid">${teams.map(team=>`<label><img src="${team.flag}" alt="">${team.name}<input type="number" min="1" max="100" value="${state.teamStrengths[team.id]??50}" data-rating="${team.id}"></label>`).join('')}</div>`:''}`;
    if(step===6)body=`<h2>PRESELECT FINALISTS? <small>OPTIONAL</small></h2><div class="toggle-row"><button class="choice ${state.preselectedFinalists.length===0?'active':''}" data-finalists="no">NO</button><button class="choice ${state.preselectedFinalists.length===2?'active':''}" data-finalists="yes">YES</button></div>${state.preselectedFinalists.length===2?`<div class="finalist-picks">${[0,1].map(i=>`<label>FINALIST ${i+1}<select data-finalist="${i}">${teams.map(team=>`<option value="${team.id}" ${state.preselectedFinalists[i]===team.id?'selected':''}>${team.name}</option>`).join('')}</select></label>`).join('')}</div>`:''}`;
    if(step===7)body=`<h2>PRESELECT CHAMPION? <small>OPTIONAL</small></h2><div class="toggle-row"><button class="choice ${!state.preselectedChampion?'active':''}" data-champion="no">NO</button><button class="choice ${state.preselectedChampion?'active':''}" data-champion="yes">YES</button></div>${state.preselectedChampion?`<label class="setup-label">CHAMPION<select id="champion">${teams.map(team=>`<option value="${team.id}" ${state.preselectedChampion===team.id?'selected':''}>${team.name}</option>`).join('')}</select></label>`:''}`;
    if(step===8){const check=validateTournamentConfig(state);body=`<h2>REVIEW TOURNAMENT</h2><div class="review"><h3>${esc(state.tournamentTitle)}</h3><div class="review-meta"><p><strong>TOURNAMENT TYPE</strong><span>${preset.label}</span></p><p><strong>TEAMS</strong><span>${state.teamCount}</span></p><p><strong>CONFEDERATION</strong><span>${state.allowInvitedTeams?'CONMEBOL + INVITED':state.confederationFilter}</span></p></div><div class="review-groups">${letters.map(letter=>`<section><strong>GROUP ${letter}</strong>${state.groups[letter].map(id=>{const team=TEAMS.find(t=>t.id===id);return team?`<span><img src="${team.flag}" alt="">${team.name}</span>`:'<span>TEAM REQUIRED</span>';}).join('')}</section>`).join('')}</div><p><strong>TEAM STRENGTH:</strong> ${state.teamStrengthEnabled?'Custom':'Balanced'}</p><p><strong>PRESELECTED FINALISTS:</strong> ${state.preselectedFinalists.length?state.preselectedFinalists.map(id=>TEAMS.find(t=>t.id===id)?.name).join(' / '):'None'}</p><p><strong>PRESELECTED CHAMPION:</strong> ${state.preselectedChampion?TEAMS.find(t=>t.id===state.preselectedChampion)?.name:'None'}</p>${check.valid?'':`<div class="validation">${check.errors.join('<br>')}</div>`}</div>`;}
    root.innerHTML=`<div class="setup-card"><header><span>MARBLE FOOTBALL</span><b>TOURNAMENT GENERATOR</b><small>STEP ${step} OF 8</small></header><div class="setup-body">${body}<div id="validation" class="validation"></div></div><footer>${step>1?'<button id="back">BACK</button>':'<span></span>'}<button id="next">${step===8?'START TOURNAMENT':'NEXT'}</button></footer></div>`;bind();requestAnimationFrame(()=>{if(!root.contains(document.activeElement)){const preferred=root.querySelector('.choice.active,[data-team-trigger],#title,button:not(#back):not(#next),input,select,#next');preferred?.focus({preventScroll:true});}});
  };
  const fail=message=>root.querySelector('#validation').textContent=message;
  const bind=()=>{
    root.querySelectorAll('[data-type]').forEach(button=>button.onclick=()=>{state=createTournamentConfig({tournamentType:button.dataset.type});render();});
    root.querySelector('#title')?.addEventListener('input',event=>state.tournamentTitle=event.target.value);
    root.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>resetWith({confederationFilter:button.dataset.filter}));
    root.querySelectorAll('[data-count]').forEach(button=>button.onclick=()=>resetWith({teamCount:Number(button.dataset.count)}));
    root.querySelectorAll('[data-invites]').forEach(button=>button.onclick=()=>resetWith({allowInvitedTeams:button.dataset.invites==='yes'}));
    root.querySelectorAll('[data-team-trigger]').forEach(trigger=>trigger.onclick=event=>{event.stopPropagation();const component=trigger.closest('[data-team-select]'),popup=component.querySelector('[data-team-popup]'),search=component.querySelector('[data-team-search]'),results=component.querySelector('[data-team-results]'),group=trigger.dataset.group,index=Number(trigger.dataset.index),current=state.groups[group][index];let active=0;
      const choose=id=>{state.groups[group][index]=id;state.teamStrengths=Object.fromEntries(selectedIds().map(teamId=>[teamId,state.teamStrengths[teamId]??50]));refreshTeamSelector(group,index);};
      const available=()=>{const elsewhere=new Set(Object.entries(state.groups).flatMap(([letter,ids])=>ids.filter((id,slot)=>letter!==group||slot!==index)).filter(Boolean));return eligibleTeams(state).filter(team=>!elsewhere.has(team.id));};
      const drawResults=()=>{const query=search.value.trim().toLowerCase(),matches=available().filter(team=>!query||[team.name,team.shortName,team.countryCode].some(value=>value.toLowerCase().includes(query))).sort((a,b)=>a.name.localeCompare(b.name));active=Math.min(active,Math.max(0,matches.length-1));results.innerHTML=matches.length?matches.map((team,i)=>`<button type="button" class="team-result ${i===active?'active':''}" data-team-result="${team.id}" role="option" aria-selected="${team.id===current}"><img src="${team.flag}" alt=""><span>${team.name}</span><b>${team.shortName}</b></button>`).join(''):'<span class="team-no-results">No teams found</span>';results.querySelectorAll('[data-team-result]').forEach(button=>{button.onmouseenter=()=>{active=[...results.querySelectorAll('[data-team-result]')].indexOf(button);results.querySelectorAll('[data-team-result]').forEach((row,i)=>row.classList.toggle('active',i===active));};button.onclick=()=>choose(button.dataset.teamResult);});};
      const scrollActiveResult=()=>{const row=results.querySelector('.active');if(!row)return;const top=row.offsetTop,bottom=top+row.offsetHeight;if(top<results.scrollTop)results.scrollTop=top;else if(bottom>results.scrollTop+results.clientHeight)results.scrollTop=bottom-results.clientHeight;};
      closeTeamSelectors(popup);popup.hidden=false;trigger.setAttribute('aria-expanded','true');search.value='';drawResults();requestAnimationFrame(()=>search.focus({preventScroll:true}));
      search.oninput=()=>{active=0;drawResults();};search.onkeydown=keyEvent=>{const rows=[...results.querySelectorAll('[data-team-result]')];if(keyEvent.key==='Escape'){keyEvent.preventDefault();keyEvent.stopPropagation();popup.hidden=true;trigger.setAttribute('aria-expanded','false');trigger.focus({preventScroll:true});return;}if((keyEvent.key==='ArrowDown'||keyEvent.key==='ArrowUp')&&rows.length){keyEvent.preventDefault();active=(active+(keyEvent.key==='ArrowDown'?1:-1)+rows.length)%rows.length;drawResults();scrollActiveResult();}if(keyEvent.key==='Enter'&&rows.length){keyEvent.preventDefault();choose(rows[active].dataset.teamResult);}};
    });
    root.querySelectorAll('[data-team-clear]').forEach(button=>button.onclick=event=>{event.stopPropagation();const group=button.dataset.group,index=Number(button.dataset.index);state.groups[group][index]='';state.teamStrengths=Object.fromEntries(selectedIds().map(id=>[id,state.teamStrengths[id]??50]));refreshTeamSelector(group,index);});
    root.querySelectorAll('[data-strength]').forEach(button=>button.onclick=()=>{state.teamStrengthEnabled=button.dataset.strength==='yes';render();});root.querySelectorAll('[data-rating]').forEach(input=>input.oninput=()=>state.teamStrengths[input.dataset.rating]=Number(input.value));
    root.querySelectorAll('[data-finalists]').forEach(button=>button.onclick=()=>{state.preselectedFinalists=button.dataset.finalists==='yes'?selectedIds().slice(0,2):[];if(state.preselectedChampion&&state.preselectedFinalists.length&&!state.preselectedFinalists.includes(state.preselectedChampion))state.preselectedChampion=null;render();});root.querySelectorAll('[data-finalist]').forEach(select=>select.onchange=()=>state.preselectedFinalists[Number(select.dataset.finalist)]=select.value);
    root.querySelectorAll('[data-champion]').forEach(button=>button.onclick=()=>{state.preselectedChampion=button.dataset.champion==='yes'?(state.preselectedFinalists[0]??selectedIds()[0]):null;render();});root.querySelector('#champion')?.addEventListener('change',event=>state.preselectedChampion=event.target.value);
    root.querySelector('#back')?.addEventListener('click',()=>{step--;render();});root.querySelector('#next').onclick=()=>{if(step===2&&!state.tournamentTitle.trim())return fail('Enter a tournament title.');if(step===4&&new Set(selectedIds()).size!==state.teamCount)return fail('Every team slot must contain a unique team.');if(step===5&&state.teamStrengthEnabled&&Object.values(state.teamStrengths).some(n=>n<1||n>100))return fail('Every team strength must be between 1 and 100.');if(step===6&&state.preselectedFinalists.length===2&&state.preselectedFinalists[0]===state.preselectedFinalists[1])return fail('Finalists must be different teams.');if(step===7&&state.preselectedChampion&&state.preselectedFinalists.length===2&&!state.preselectedFinalists.includes(state.preselectedChampion))return fail('Champion must be one of the selected finalists.');if(step<8){step++;render();return;}const result=validateTournamentConfig(state);if(!result.valid)return fail(result.errors.join(' '));document.removeEventListener('pointerdown',dismissTeamSelectors);document.removeEventListener('keydown',remoteNavigation);root.remove();resolve(result.config);};
  };render();
});}
